name: CI for sales-taxes-problem

on:
  push:
    branches: [ staging, master ]
  pull_request:
    branches: [ staging, master ]

jobs:
  build-and-test:
    runs-on:  macos-10.15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.3

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project false
        poetry config cache-dir ~/.poetry
        poetry config virtualenvs.path ~/.poetry/venv

    - name: Store Poetry cache
      uses: actions/cache@v2
      id: poetry-cache
      with:
        path: ~/.poetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependecies
      if: steps.poetry-cache.outputs.cache-hit != 'true'
      run: poetry install -vv

    - name: Run Black
      run:  poetry run black --check .

    - name: Run MyPy
      run: poetry run mypy --strict ./sales-taxes-problem

    - name: Run isort
      run: poetry run isort -c

    - name: Run Pytest with coverage threshold
      # FIXME: increase the code coverage
      run: poetry run pytest --cov-fail-under=0 --cov=./sales-taxes-problem
      
